name: lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --no-root --with dev

      - name: ruff
        run: poetry run ruff check app/

      - name: mypy
        run: poetry run mypy

      - name: vulture
        run: poetry run vulture
